name: HTML Lint
on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Lint HTML
        uses: yeliben/code-linter-action@v1.0.0
        with:
          files: 'public/*.php'
