name: PHPStan
on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: composer install
      - run: vendor/bin/phpstan analyse
